apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis-ctrl-center
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: redis-ctrl-center
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-ctrl-center
        image: {{ redis_docker_image }}
        imagePullPolicy: IfNotPresent
        env:
        - name: MODE
          value: "cluster_ctrl"
        - name: REDIS_CLUSTER_REPLICAS
          value: "{{ redis_cluster_replicas }}"
        - name: LOG_LEVEL
          value: "{{ log_level }}"
        - name: API_SERVER_ADDR
          value: "{{ api_server_addr }}"
        - name: REDIS_PORT
          value: "{{ redis_server_port }}"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: {{ redis_server_port }}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-cluster-node
spec:
  serviceName: "redis-cluster-svc"
  replicas: {{ redis_replicas }}
  template:
    metadata:
      labels:
        name: redis-cluster-node
        app: redis
    spec:
      hostNetwork: {{ hostnetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-cluster-node
        image: {{ redis_docker_image }}
        imagePullPolicy: IfNotPresent
        env:
        - name: MODE
          value: "cluster"
        - name: REDIS_CLUSTER_REPLICAS
          value: "{{ redis_cluster_replicas }}"
        - name: LOG_LEVEL
          value: "{{ log_level }}"
        - name: API_SERVER_ADDR
          value: "{{ api_server_addr }}"
        - name: REDIS_PORT
          value: "{{ redis_server_port }}"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: {{ redis_server_port }}
        volumeMounts:
  {% if persistent_flag %}
        - name: redisdata
          mountPath: /data/redis
  {% endif %}
        securityContext:
          capabilities: {}
          privileged: true
  {% if persistent_flag %}
  volumeClaimTemplates:
  - metadata:
      name: redisdata
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ redis_data_size }}Gi
  {% endif %}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-svc
  labels:
    name: redis-cluster-svc
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: {{ redis_server_port }}
  clusterIP: None
  selector:
    name: sts-redis-cluster
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-svc-np
  labels:
    name: redis-cluster-svc-np
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: {{ redis_server_port }}
    nodePort: {{ redis_server_nodeport }}
  type: NodePort
  selector:
    name: sts-redis-cluster