apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sts-redis-ct
spec:
  serviceName: "svc-redis-ct"
  replicas: 1
  template:
    metadata:
      labels:
        name: sts-redis-ct
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: cntr-redis-ct
        image: h3crd-wlan1.chinacloudapp.cn:5000/java:alpha
        imagePullPolicy: Always
        ports:
        - containerPort: 6379