apiVersion: v1
kind: Service
metadata:
  name: svc-redis-master
  labels:
    name: svc-redis-master
spec:
  ports:
  - port: 6379
    targetPort: 6379
  clusterIP: None
  selector:
    name: sts-redis-master
---
apiVersion: v1
kind: Service
metadata:
  name: svc-redis-sentinel
  labels:
    name: svc-redis-sentinel
spec:
  ports:
  - port: 26379
    targetPort: 26379
  clusterIP: None
  selector:
    name: sts-redis-sentinel
---
apiVersion: v1
kind: Service
metadata:
  name: svc-redis-slave
  labels:
    name: svc-redis-slave
spec:
  ports:
  - port: 6379
    targetPort: 6379
  clusterIP: None
  selector:
    name: sts-redis-slave
