apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sts-redis-cc
spec:
  serviceName: "svc-redis-cc"
  replicas: 1
  template:
    metadata:
      labels:
        name: sts-redis-cc
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: cntr-redis-cc
        image: YourImage
        imagePullPolicy: Always
        env:
        - name: CLUSTER_CTRL
          value: "true"
        - name: CLUSTER_SVC
          value: "svc-redis-cluster"
        - name: REDIS_CLUSTER_SLAVE_QUANTUM
          value: "1"
        - name: API_SERVER_ADDR
          value: "172.20.0.12:8080"
        - name: REDIS_PORT
          value: "6380"
        ports:
        - containerPort: 6380