apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sts-redis-slave
spec:
  serviceName: "svc-redis-slave"
  replicas: 3
  template:
    metadata:
      labels:
        name: sts-redis-slave
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: cntr-redis-slave
        image: YourImage
        imagePullPolicy: Always
        env:
        - name: SLAVE
          value: "true"
        - name: MASTER_HOST
          value: sts-redis-master-0.svc-redis-master
        - name: MASTER_PORT
          value: "6379"
        - name: SENTINEL_HOST
          value: sts-redis-sentinel-0.svc-redis-sentinel 
        - name: SENTINEL_PORT
          value: "26379"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redisslave
          mountPath: /data/redis
        securityContext:
          capabilities: {}
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: redisslave
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
