apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis-cluster-ctrl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: redis-cluster-ctrl
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-cluster-ctrl
        image: redis:0601
        imagePullPolicy: IfNotPresent
        env:
        - name: MODE
          value: "CLUSTERCTRL"
        - name: LOG_LEVEL
          value: "info"
        - name: API_SERVER_ADDR
          value: "172.27.25.35:8080"
        - name: REDIS_PORT
          value: "6380"
        - name: REBALANCE_DELAY
          value: "30"
        - name: TOLERANCE
          value: "1"
        - name: WAIT_TIMEOUT
          value: "30"
        - name: STATEFULSET_REPLICAS
          value: "3"
        - name: CLUSTER_REPLICAS
          value: "0"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 6380
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-cluster-node
spec:
  serviceName: "redis-cluster-svc"
  replicas: 3
  template:
    metadata:
      labels:
        name: redis-cluster-node
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-cluster-node
        image: redis:0601
        imagePullPolicy: IfNotPresent
        env:
        - name: MODE
          value: "CLUSTERNODE"
        - name: LOG_LEVEL
          value: "info"
        - name: API_SERVER_ADDR
          value: "172.27.25.35:8080"
        - name: REDIS_PORT
          value: "6380"
        - name: REBALANCE_DELAY
          value: "30"
        - name: TOLERANCE
          value: "1"
        - name: WAIT_TIMEOUT
          value: "30"
        - name: STATEFULSET_REPLICAS
          value: "3"
        - name: CLUSTER_REPLICAS
          value: "0"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 6380
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-svc
  labels:
    name: redis-cluster-svc
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6380
  clusterIP: None
  selector:
    name: redis-cluster-node
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-svc-np
  labels:
    name: redis-cluster-svc-np
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6380
    nodePort: 6379
  type: NodePort
  selector:
    name: redis-cluster-node